Ftp combine move remove
shipyardapp/ftp-blueprints pull request #4
Opened 2022-10-26 15:13 UTC by wrp801

Adding the ability to move and remove files on an FTP server

2022-11-08 19:32 UTC, blakeburch requested changes
Code _looks_ fine. Regex functionality has some issues.

1. When moving a file using regex, the matching logic appears to be wrong. If I leave the source_folder_name blank, it only searches for files in the root directory, rather than using that input as a "filter" value. So if a file should match in different subdirectories, it doesn't find it.

This happens for both move and delete functions.

2022-11-08 19:32 UTC, blakeburch commented on ftp_blueprints/move_file.py
> +            print(f'Moving file {index+1} of {len(matching_file_names)}')
No need for +1 here since you started at 1. It ends up saying "moving file 2 of 1".

2022-11-08 20:22 UTC, wrp801 commented
@blakeburch just so I understand here, you’re saying that if I provide the pattern as `.csv` and it doesn’t find any matches in the root directory, it should also search the directories within the root to see if there are matches?

2022-11-08 20:36 UTC, blakeburch commented
yes. It should recursively look through all subdirectories to see if there are matches.

This is how every other Blueprint works with regex matching logic.

This situation should be accounted for in our documentation. See “enumerated destination files” example. <https://www.shipyardapp.com/docs/reference/blueprints/blueprint-library/match-type/#regex-match>

2022-11-08 20:57 UTC, wrp801 commented
Okay cool, that makes sense

2022-11-14 17:42 UTC, blakeburch approved these changes
Good to launch.

2022-11-14 18:06 UTC, merged